global:
  hosts:
    web: "nessus-sandbox.nextgl.com"
  imagePullSecrets: [{"name": "regcred"}]

replicaCount: 1

service:
  enabled: true
  port: 8834
  type: NodePort 

storage:
  enabled: enabled
  capacity: "50Gi"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx-internal"
  tls: []
  hosts:
    - host: "{{ .Values.global.hosts.web }}"
      paths:
        - path: /
